version: '3.8'
services:
  database:
    image: mysql/mysql-server:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'valentinroot'
      MYSQL_DATABASE: 'ui_problem'
      MYSQL_USER: 'valentin'
      MYSQL_PASSWORD: 'valentin'
      MYSQL_ROOT_HOST: '%'
    ports:
      - "9906:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/database_schema.sql:/docker-entrypoint-initdb.d/entry_schema.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: 'valentinroot'
      PMA_HOST: database
      PMA_USER: 'valentin'
      PMA_PASSWORD: 'valentin'
      
    ports:
       - 8001:80
    depends_on:
      - database
  symfony:
    build:
      context: ./symfony_user_api
      dockerfile: Dockerfile
    container_name: symfony
    ports:
      - "8000:8000"
    depends_on:
      - database

  angular:
    build:
      context: ./angular_front
      dockerfile: Dockerfile
    container_name: angular_front
    ports:
      - "3000:80"
    depends_on:
      - symfony

volumes:
  db_data: {}